FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y wget \
                    python3 \ 
                    libevent-core-2.1-7 \
                    libhwloc-dev \
                    libevent-pthreads-2.1-7

# install openmpi with cuda support.
RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.1.tar.gz
RUN tar -zxvf openmpi-4.1.1.tar.gz
WORKDIR openmpi-4.1.1/
RUN ./configure --with-cuda --enable-mpi-cxx --prefix=/opt/openmpi-4.1.1
RUN make -j8 install
ENV LD_LIBRARY_PATH=/usr/local/lib:/opt/openmpi-4.1.1/lib/:$LD_LIBRARY_PATH
ENV PATH=/opt/openmpi-4.1.1/bin/:$PATH
RUN ln -s /usr/bin/python3.8 /usr/bin/python

WORKDIR /MGG